const goods = [
    {
        article: "c_01_01_01",
        imagePATH: "Curtains1.jpg",
        material: "Поліестер",
        producer: "Германія",
        price: 1500,
        protection: "8/10",
        care: "Прати при 18 градусах",
    },
    {
        article: "c_01_01_02",
        imagePATH: "Curtains3.jpg",
        material: "Хлопок",
        producer: "Германія",
        price: 1600,
        protection: "8/10",
        care: "Прати при 18 градусах",
    },
    {
        article: "c_01_01_03",
        imagePATH: "Curtains6.jpg",
        material: "Льон",
        producer: "Германія",
        price: 1750,
        protection: "8/10",
        care: "Прати при 18 градусах",
    }, {
        article: "c_01_01_04",
        imagePATH: "Curtains9.jpg",
        material: "Хлопок",
        producer: "Поліестер м'який",
        price: 1450,
        protection: "8/10",
        care: "Прати при 18 градусах",
    },
    {
        article: "c_01_02_01",
        imagePATH: "Curtains6.jpg",
        material: "Хлопок",
        producer: "Поліестер м'який",
        price: 1450,
        protection: "8/10",
        care: "Прати при 18 градусах",
    }, {
        article: "c_01_02_02",
        imagePATH: "Curtains9.jpg",
        material: "Льон",
        producer: "Поліестер м'який",
        price: 1450,
        protection: "8/10",
        care: "Прати при 18 градусах",
    },
    {
        article: "t_01_01_01",
        imagePATH: "Tulle2.jpg",
        material: "Льон",
        producer: "Поліестер м'який",
        price: 1450,
        protection: "8/10",
        care: "Прати при 18 градусах",
    }, {
        article: "c_01_02_02",
        imagePATH: "Tulle4.jpg",
        material: "Льон",
        producer: "Поліестер м'який",
        price: 1600,
        protection: "8/10",
        care: "Прати при 18 градусах",
    },
]

module.exports = goods